# Generated by Django 6.1.1 on 2026-10-05 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoques', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoque',
            options={'ordering': ['prateleira'], 'verbose_name': 'Estoque', 'verbose_name_plural': 'Gerenciador de Estoques'},
        ),
    ]
