# Generated by Django 6.1.1 on 2026-10-08 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoques', '0002_alter_estoque_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoque',
            options={'ordering': ['prateleira'], 'verbose_name': 'Estoque', 'verbose_name_plural': 'Estoques'},
        ),
    ]
