# Generated by Django 6.1.1 on 2026-10-05 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estoque',
        ),
    ]
