# Generated by Django 6.1.1 on 2026-10-05 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_delete_estoque'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['produto_nome'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Gerenciador de Produtos'},
        ),
    ]
